- Protocol_name: 18 pairwise tests (130K)

- save_models: False
- save_datasets: False
- save_graphs: True
- save_nothing: False
#- results_path: C:\Users\xsj110\OneDrive - University of Copenhagen\Master\02 AI Lab\43 article 30n

# - unique_initial_sample:
#     sample_size: 10

- Experiment:
    name: rdkit2D pairwise
    replicate: 30

    dataset: /home/jmni/MDRMF/datasets/DTP_rdkit2D_shuffled.pkl

    model:
        name: RFModellerPairwise
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy
        use_pairwise: True

    metrics: 
        names: [top-k, top-k-acquired]
        k: [1320]               